name: DiT-FasterDiffusion
channels:
  - pytorch
  - nvidia
dependencies:
  - python == 3.8
  - pytorch == 1.13.0
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - timm
    - diffusers==0.27.2
    - accelerate
    - numpy==1.20.0
    # guided-diffusion and evaluations
    - -e git+https://github.com/openai/guided-diffusion.git#egg=guided_diffusion
    - mpi4py-mpich
    - protobuf==3.20.0
    - tensorflow-gpu==2.2.0
